-- MySQL Script generated by MySQL Workbench
-- Fri Apr  8 17:52:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipousuario` (
  `idtipousuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT 'admin' COMMENT 'Os tipos de usuário serão ‘admin’ e ‘user’.',
  PRIMARY KEY (`idtipousuario`))
;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` TEXT NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  CONSTRAINT `tipousuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`tipousuario` (`idtipousuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table `mydb`.`editora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`editora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`editora` (
  `ideditora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideditora`),
  UNIQUE INDEX `ideditora_UNIQUE` (`ideditora` ASC) VISIBLE)
;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `idLivro` VARCHAR(45) NULL,
  PRIMARY KEY (`idautor`),
  CONSTRAINT `idEditora`
    FOREIGN KEY (`idautor`)
    REFERENCES `mydb`.`editora` (`ideditora`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table `mydb`.`livros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livros` (
  `idLivros` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `ano` INT NULL,
  `resumo` TEXT NULL,
  `editora` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `situacao` VARCHAR(45) NOT NULL DEFAULT 'Não lido',
  PRIMARY KEY (`idLivros`),
  CONSTRAINT `autor`
    FOREIGN KEY (`idLivros`)
    REFERENCES `mydb`.`autor` (`idautor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idLivros`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
